<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:

  server7:
    roles:
      - default
      - ldap
      - nfs_server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE

  client7:
    roles:
      - client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE

  server8:
    roles:
      - nfs_server
      - 389ds
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/unstable/6/el/8/x86_64/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE

  client8:
    roles:
      - client
      - agent
      - el8
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: <%= hypervisor %>
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/unstable/6/el/8/x86_64/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  synced_folder: disabled
  # vb_gui: true
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
  # The following was added because ssh was timing out on gitlab servers
  ssh:
    keepalive: true
    keepalive_interval: 10
    keepalive_maxcount: 60
